name: CI via GitHub Actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  my-job:
    name: Lint, Test + Test Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1

      - run: bun install
      - run: bunx eslint .
      - run: bun test --coverage
      - run: if [ $? -eq 1 ]; then echo "Coverage failed"; fi
