name: CI Pipeline via GitHub Actions
permissions:
  contents: read

on:
  push:

jobs:
  list-test-coverage:
    name: Lint, Test + Test Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76
      - run: bun install
      - run: bun lint
      - run: bun test --coverage
      - run: if [ $? -eq 1 ]; then echo "Coverage failed"; fi
